### ISSUE TITLE
Sovereign Chess: Can't defect

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#7]
<https://www.infinitepigames.com/sc-rules>
Rule 15 is "A player may replace their king with a king of a different color they control, which constitutes their move—unless this leaves the king on a square of its own color, in which case it must then make a move". There is also a section called "Regime Change", in which defection is listed as a method of regime change.

Defection isn't implemented in this [repository's Sovereign Chess](https://glukkazan.github.io/checkmate/sovereign-chess-board.htm).

**Comment by GlukKazan** [comment]
This is a very difficult rule to implement. I have not yet figured out how to do it in Dagaz.

**Comment by acornmonkey** [comment]
I could understand your claim that defection is too difficult to implement if you hadn't already implemented overthrowing. But I reckon that the hardest parts of implementing defection are already implemented in overthrowing. Defection is not significantly harder to implement than overthrowing.

Overthrowing: Pawn promotes to king and its colour becomes the player's colour. Original king is removed.
Defection: King changes colour and its new colour becomes the player's colour. If it could castle, it still can.

Rather than thinking of defection as the king changing colour, it may be better to think of it as adding a new king and removing the old one. Just like if you were to play the game with a physical Sovereign Chess set.

**Comment by GlukKazan** [comment]
I'll try to explain my difficulty. The technical difficulty lies in the need to transform the king "on the spot", without moving it. Due to the peculiarities of the implementation, such moves do not work very well, first of all, from the point of view of the UI. A piece should turn into another when you click on it. The user can misclick by changing the piece, although he did not want to do this. Even worse, if the piece can make other moves, with moving. Moving a piece starts with a click on it, and if the logic of changing "in place" works, that's it. In Sovering Chess, it's even more complicated: by clicking on the shape, a dialog should open with the choice of an available color for promotion. All this is very difficult and I'm not ready to deal with it now. At the same time, the promotion of a pawn into a new king works, including with a change in color, since there is no need to change the piece "on the spot".

**Comment by acornmonkey** [comment]
I'm thinking that maybe you could right-click the king to defect. The dialog will be similar to the promotion one. And the game already knows which colours the player controls. Unavailable colours should be hidden. Since there are 12 colours in this game, all 12 would have to be shown, every time, if unavailable colours weren't hidden. If there are no defections available, the game should show an alert saying "There is no color to defect to", or something, instead of the defection dialog which would be blank.

**Comment by GlukKazan** [comment]
I came up with another way, but it will take me some time to do it.

**Comment by GlukKazan** [comment]
I added kings of different colors on the left. Only those whose color the player controls (other than their own color) are visible. Each of these pieces can go to the place of the king, replacing it. This is the simplest solution I have found.

Fixed: https://github.com/GlukKazan/GlukKazan.github.io/commit/02cfa6086d9d22d544889ec19740cc3be47ee8e9
